[platformio]
default_envs = esp32

[env:esp32]
platform = espressif32
board = esp32thing_plus
framework = arduino
build_src_filter = +<esp32/*> -<OpenLog_Artemis_GNSS_Logging_Modified/*>
lib_deps =
    BotleticsSIM7000
    https://github.com/adafruit/Adafruit_INA228
    sparkfun/SparkFun u-blox GNSS Arduino Library
    Adafruit Unified Sensor

[env:openlog_artemis]
platform = https://github.com/nigelb/platform-apollo3blue
board = SparkFun_RedBoard_Artemis_ATP
framework = arduino
build_src_filter = +<OpenLog_Artemis_GNSS_Logging_Modified/*> -<esp32/*>
platform_packages = framework-arduinoapollo3@https://github.com/sparkfun/Arduino_Apollo3#v2.2.0
lib_deps =
    sparkfun/SparkFun u-blox GNSS v3
    https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary
    https://github.com/greiman/SdFat
